---
#Configuration stuff

# Composer configuration
composer_path: /usr/bin/composer
composer_home_path: '/home/vagrant/.composer'

# MariaDB settings
mysql_packages:
  - mariadb-common
  - mariadb-client
  - mariadb-server
mysql_config_file: /etc/mysql/my.cnf
mysql_socket: /var/run/mysqld/mysqld.sock
overwrite_global_mycnf: yes
mysql_enabled_on_startup: yes


mysql_port: "3306"
mysql_bind_address: '0.0.0.0'
mysql_datadir: /var/lib/mysql
mysql_root_password: root
mysql_root_password_update: yes
mysql_wait_timeout: 300

mysql_databases:
  - name: "ticketing_db"
    encoding: utf8
    collation: utf8_general_ci

mysql_users:
  - name: "ticketing_dbu"
    host: "192.168.33.%"
    password: "Ticket1ngPa55word!"
    priv: "ticketing_db.*:ALL"
  - name: "ticketing_dbu"
    host: "localhost"
    password: "Ticket1ngPa55word!"
    priv: "ticketing_db.*:ALL"

# Nginx Virtual hosts
nginx_remove_default_vhost: true
nginx_hosts:
  - server_name: "ticketdev.local"
    root: "/var/www/html/web"
    index: "app.php index.php index.html index.htm"
    is_php: true

# PHP
php_packages:
  - php5
  - php5-mcrypt
  - php5-cli
  - php5-common
  - php5-curl
  - php5-dev
  - php5-fpm
  - php5-gd
  - php-pear
  - php-apc
  - php5-intl
  - libpcre3-dev
php_webserver_daemon: "nginx"
php_enable_php_fpm: true
php_use_managed_ini: true
php_memory_limit: "192M"
php_display_errors: "On"
php_display_startup_errors: "On"
php_realpath_cache_size: "1024K"
php_sendmail_path: "/usr/sbin/ssmtp -t"
php_opcache_enabled_in_ini: true
php_opcache_memory_consumption: "192"
php_opcache_max_accelerated_files: 4096
php_timezone: "Europe/London"
