<?php

namespace Cferthorney\TicketBundle\Entity;

/**
 * EntitiesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EntitiesRepository extends \Doctrine\ORM\EntityRepository
{
}
