---
- hosts: all

  vars_files:
    - vars/config.yml

  pre_tasks:
      - include: tasks/init-debian.yml
        when: ansible_os_family == 'Debian'

  roles:
  #   # Essential roles.
    - geerlingguy.nginx
    - geerlingguy.mysql
    - geerlingguy.php
    - geerlingguy.php-pecl
    - geerlingguy.php-mysql
    - geerlingguy.composer

  tasks:
    - include: tasks/nginx.yml
