---
  - src: geerlingguy.nginx
    path: roles/
  - src: geerlingguy.mysql
    path: roles/
  - src: geerlingguy.php
    path: roles/
  - src: geerlingguy.php-pecl
    path: roles/
  - src: geerlingguy.php-mysql
    path: roles/
  - src: geerlingguy.composer
    path: roles/
  - src: geerlingguy.php-xdebug
    path: roles/
  - src: geerlingguy.php-xhprof
    path: roles/